import { Exercise } from '../../domain/entities/Exercise';
import { IExerciseRepository } from '../../domain/repositories';
import { Tense } from '../../domain/value-objects';
import { CreateExerciseDto } from './dto/CreateExerciseDto';
import { ExerciseResponseDto } from './dto/ExerciseResponseDto';

export class ExerciseService {
	constructor(private readonly exerciseRepository: IExerciseRepository) {}

	async create(dto: CreateExerciseDto): Promise<ExerciseResponseDto> {
		const exercise = new Exercise(
			'', // id will be generated by repository
			dto.tense,
			dto.question,
			dto.answer,
			dto.explanation,
			new Date(), // createdAt
			new Date(), // updatedAt
		);
		const createdExercise = await this.exerciseRepository.create(exercise);
		return this.toDto(createdExercise);
	}

	async findRandom(tenses: Tense[], limit: number): Promise<ExerciseResponseDto[]> {
		const exercises = await this.exerciseRepository.findRandom(tenses, limit);
		return exercises.map(this.toDto);
	}

	private toDto(exercise: Exercise): ExerciseResponseDto {
		return {
			id: exercise.id,
			tense: exercise.tense,
			question: exercise.question,
			answer: exercise.answer,
			explanation: exercise.explanation,
			createdAt: exercise.createdAt,
			updatedAt: exercise.updatedAt,
		};
	}
}
