-- CreateEnum
CREATE TYPE "Tense" AS ENUM ('PRESENT_SIMPLE', 'PRESENT_CONTINUOUS', 'PRESENT_PERFECT', 'PRESENT_PERFECT_CONTINUOUS', 'PAST_SIMPLE', 'PAST_CONTINUOUS', 'PAST_PERFECT', 'PAST_PERFECT_CONTINUOUS', 'FUTURE_SIMPLE', 'FUTURE_CONTINUOUS', 'FUTURE_PERFECT', 'FUTURE_PERFECT_CONTINUOUS');

-- CreateTable
CREATE TABLE "tense_exercise_questions" (
    "id" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "answer" TEXT NOT NULL,
    "tense" "Tense" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tense_exercise_questions_pkey" PRIMARY KEY ("id")
);
