export const Tense = {
	PRESENT_SIMPLE: 'PRESENT_SIMPLE',
	PRESENT_CONTINUOUS: 'PRESENT_CONTINUOUS',
	PRESENT_PERFECT: 'PRESENT_PERFECT',
	PRESENT_PERFECT_CONTINUOUS: 'PRESENT_PERFECT_CONTINUOUS',
	PAST_SIMPLE: 'PAST_SIMPLE',
	PAST_CONTINUOUS: 'PAST_CONTINUOUS',
	PAST_PERFECT: 'PAST_PERFECT',
	PAST_PERFECT_CONTINUOUS: 'PAST_PERFECT_CONTINUOUS',
	FUTURE_SIMPLE: 'FUTURE_SIMPLE',
	FUTURE_CONTINUOUS: 'FUTURE_CONTINUOUS',
	FUTURE_PERFECT: 'FUTURE_PERFECT',
	FUTURE_PERFECT_CONTINUOUS: 'FUTURE_PERFECT_CONTINUOUS',
} as const;

export type Tense = (typeof Tense)[keyof typeof Tense];
